language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
env:
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.10
  - DJANGO_VERSION=1.8.6
install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -e .
  - pip install -r .travis-requirements.txt
script:
  coverage run --source=tiny_rest testproject/manage.py test
after_success:
  coveralls
